### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by netfun81** [alexkh/ywm#1]
I got an error when running mk.   When i looked at the contents of mk, i noticed -lX11 for both y_move and y_resize.  Changing that to -lxcb allowed everything to compile and install.   ywm would segfault when launched, changing the fonts to fixed in ywm.cpp corrected that issue.  It then started properly and the 3 xterms are lauched.  I could maximize with backbutton + middle button and close a window with backbutton + up.   However, the move and resize did not work.  

I changed the line with execve("/usr/share/control/bin/wmove_pointer",  in ywm.cpp to
execve("/usr/bin/y_move",
and also the other line to y_resize and everything seems to be working.

**Comment by alexkh** [comment]
k, thanks a lot for your help, I will update the code accordingly.

**Comment by alexkh** [comment]
k, code updated, thanks again. I think this issue can be closed now...
